# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMS-O2
version:      0.020
version_from: O2.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    Net::SMS::Web:                 0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
